/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_um2015_testndk_MainActivity.h"
/* Header for class com_example_um2015_testndk_MainActivity */
/*
 * Class:     com_example_um2015_testndk_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_um2015_testndk_MainActivity_getStringFromNative
  (JNIEnv *env, jobject obj){
  return (*env)->NewStringUTF(env,"Hello From JNI");
  }

